"""Create Task table

Revision ID: 2d7e1b2a4e73
Revises: 
Create Date: 2023-05-26 22:15:15.965422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7e1b2a4e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(length=150), nullable=True),
    sa.Column('task_content', sa.String(), nullable=True),
    sa.Column('days_of_week', sa.String(), nullable=False),
    sa.Column('repeat_weekly', sa.Boolean(), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
